from .test_modules.authentication_tests.test_authentication_gui import *
from .test_modules.authentication_tests.test_instance_user import *
from .test_modules.authentication_tests.test_login import *
from .test_modules.authentication_tests.test_register import *
from .test_modules.calendar_tests.calendar_display_tests import *
from .test_modules.calendar_tests.date_utilities_tests import *
from .test_modules.calendar_tests.month_view_tests import *
from .test_modules.calendar_tests.month_year_navigation_tests import *
from .test_modules.calendar_tests.task_details_tests import *
from .test_modules.dashboard_tests.test_dashboard_data import *
from .test_modules.dashboard_tests.test_dashboard import *
from .test_modules.dashboard_tests.test_plot import *
from .test_modules.filter_tests.test_filter import *
from .test_modules.history_tests.test_display_history import *
from .test_modules.history_tests.test_history import *
from .test_modules.homepage_tests.test_homepage import *
from .test_modules.items_tests.labels_tests.labels_page_tests import *
from .test_modules.items_tests.project_tests.project_tests import *
from .test_modules.items_tests.project_tests.project_create_page_tests import *
from .test_modules.items_tests.project_tests.project_manager_tests import *
from .test_modules.items_tests.subtask_tests.subtask_create_page_tests import *
from .test_modules.items_tests.subtask_tests.subtask_page_tests import *
from .test_modules.items_tests.tasks_tests.task_create_page_tests import *
from .test_modules.items_tests.tasks_tests.task_manager_tests import *
from .test_modules.items_tests.tasks_tests.task_page_tests import *
from .test_modules.load_tests.load import *
